name: Deploy
env:
  ENV_FILE: ${{ secrets.ENV_FILE }}
  
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  setup-build-publish-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Create .env
      run: |
         echo ${ENV_FILE} >> .env
    - name: Deploy
      uses: google-github-actions/deploy-appengine@main
      with:
        credentials: ${{ secrets.gcp_credentials }}
        project_id: ${{ secrets.project_id }}
        promote: true
